config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :writers

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :writer

  validates :name, presence: true, length: { minimum: 2, maximum: 199 }
  validates :writer, presence: true
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :books

  validates :name, presence: true, length: { minimum: 2, maximum: 99 }
  validates :bio, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.includes(:writer).order(:name)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: t('book.created')
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to books_path, notice: t('book.updated')
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :writer_id, :summary)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  def index
    @writers = Writer.all
  end

  def new
    @writer = Writer.new
  end

  def edit
    @writer = Writer.find(params[:id])
  end

  def create
    @writer = Writer.new(writer_params)

    if @writer.save
      redirect_to writers_path, notice: t('writer.created')
    else
      render :new
    end
  end

  def update
    @writer = Writer.find(params[:id])

    if @writer.update(writer_params)
      redirect_to writers_path, notice: t('writer.updated')
    else
      render :edit
    end
  end

  private

  def writer_params
    params.require(:writer).permit(:name, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <%= form_with(model: @book, local: true) do |form| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@book.errors.count, "error") %> prohibited
          this book from being saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label">书名</label>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control", placeholder: "书名" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="desc" class="col-sm-2 col-form-label">作者</label>
      <div class="col-sm-10">
        <%= form.select(:writer_id, options_for_select(Writer.all.pluck(:name, :id)), {}, {class: 'required'}) %>
      </div>
    </div>

    <div class="form-group row">
      <label for="summary" class="col-sm-2 col-form-label">描述</label>
      <div class="col-sm-10">
        <%= form.text_area :summary, class: "form-control", placeholder: "描述", rows: 3 %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">修改书籍信息</button>
      </div>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="container">
  <h1>Listing books</h1>

  <%= link_to 'New book', new_book_path %>

  <table>
    <tr>
      <th>Name</th>
      <th>作者</th>
      <th>Summary</th>
      <th></th>
    </tr>

    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.writer.name %></td>
        <td><%= book.summary %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<div class="container">
  <%= form_with scope: :book, url: books_path, local: true do |form| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@book.errors.count, "error") %> prohibited
          this book from being saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label">书名</label>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control", placeholder: "书名" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="desc" class="col-sm-2 col-form-label">作者</label>
      <div class="col-sm-10">
        <%= form.select(:writer_id, options_for_select(Writer.all.pluck(:name, :id)), {}, {class: 'required'}) %>
      </div>
    </div>

    <div class="form-group row">
      <label for="summary" class="col-sm-2 col-form-label">描述</label>
      <div class="col-sm-10">
        <%= form.text_area :summary, class: "form-control", placeholder: "描述", rows: 3 %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">创建书籍</button>
      </div>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container">
  <p>
    <strong>书名:</strong>
    <%= @book.name %>
  </p>

  <p>
    <strong>Writer:</strong>
    <%= @book.writer.name %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= @book.summary %>
  </p>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic"><%= t('home.banner_title') %></h1>
      <p class="lead my-3"><%= t('home.banner_desc') %></p>
      <p class="lead mb-0"><a href="/books/5" class="text-white font-weight-bold"><%= t('home.banner_link') %>...</a></p>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-primary">World</strong>
          <h3 class="mb-0">
            <a class="text-dark" href="#">Featured post</a>
          </h3>
          <div class="mb-1 text-muted">Nov 12</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#">Continue reading</a>
        </div>
        <svg class="bd-placeholder-img card-img-right flex-auto d-none d-lg-block" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
          <title>Placeholder</title>
          <rect fill="#55595c" width="100%" height="100%"></rect>
          <text fill="#eceeef" dy=".3em" x="50%" y="50%">Thumbnail</text>
        </svg>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-success">Design</strong>
          <h3 class="mb-0">
            <a class="text-dark" href="#">Post title</a>
          </h3>
          <div class="mb-1 text-muted">Nov 11</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#">Continue reading</a>
        </div>
        <!-- This svg is the same as the previous one. -->
        <svg class="bd-placeholder-img card-img-right flex-auto d-none d-lg-block" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
          <title>Placeholder</title>
          <rect fill="#55595c" width="100%" height="100%"></rect>
          <text fill="#eceeef" dy=".3em" x="50%" y="50%">Thumbnail</text>
        </svg>
      </div>
    </div>
  </div>
</div>

<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        From the Firehose
      </h3>

      <div class="blog-post">
        <h2 class="blog-post-title">Sample blog post</h2>
        <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>

        <p>This blog post shows a few different types of content that’s supported and styled with Bootstrap. Basic typography, images, and code are all supported.</p>
        <hr>
        <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
        <blockquote>
          <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </blockquote>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <h2>Heading</h2>
        <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
        <h3>Sub-heading</h3>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
        <pre><code>Example code block</code></pre>
        <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
        <h3>Sub-heading</h3>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <ul>
          <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
          <li>Donec id elit non mi porta gravida at eget metus.</li>
          <li>Nulla vitae elit libero, a pharetra augue.</li>
        </ul>
        <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
        <ol>
          <li>Vestibulum id ligula porta felis euismod semper.</li>
          <li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>
          <li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>
        </ol>
        <p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
      </div><!-- /.blog-post -->

      <div class="blog-post">
        <h2 class="blog-post-title">Another blog post</h2>
        <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

        <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
        <blockquote>
          <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </blockquote>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
      </div><!-- /.blog-post -->

      <div class="blog-post">
        <h2 class="blog-post-title">New feature</h2>
        <p class="blog-post-meta">December 14, 2013 by <a href="#">Chris</a></p>

        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <ul>
          <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
          <li>Donec id elit non mi porta gravida at eget metus.</li>
          <li>Nulla vitae elit libero, a pharetra augue.</li>
        </ul>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
      </div><!-- /.blog-post -->

      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
      </nav>

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-3 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

      <div class="p-3">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-3">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main><!-- /.container -->

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('site.name') %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="/"><%= t('site.name') %></a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3" focusable="false" role="img"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="#">传习录</a>
          <a class="p-2 text-muted" href="#">论语</a>
          <a class="p-2 text-muted" href="#">大学</a>
          <a class="p-2 text-muted" href="#">中庸</a>
          <a class="p-2 text-muted" href="#">孟子</a>
          <a class="p-2 text-muted" href=<%= writers_path %>>圣哲故事</a>
          <a class="p-2 text-muted" href="#">网络资源</a>
          <a class="p-2 text-muted" href="#">新闻</a>
          <a class="p-2 text-muted" href="#">活动</a>
          <!--      <a class="p-2 text-muted" href="#">You can add more</a>-->
        </nav>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/writers/edit.html.erb
<div class="container">
  <%= form_with(model: @writer, local: true) do |form| %>
    <% if @writer.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@writer.errors.count, "error") %> prohibited
          this writer from being saved:
        </h2>
        <ul>
          <% @writer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label">作者姓名</label>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control", placeholder: "作者姓名" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="desc" class="col-sm-2 col-form-label">作者简介</label>
      <div class="col-sm-10">
        <%= form.text_area :bio, class: "form-control", placeholder: "作者简介", rows: 3 %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">创建作者</button>
      </div>
    </div>
  <% end %>
</div>

app/views/writers/index.html.erb
<div class="container">
  <h1>Listing writers</h1>

  <%= link_to 'New writer', new_writer_path %>

  <img src='/assets/avatar.png' />

  <table>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th></th>
    </tr>

    <% @writers.each do |writer| %>
      <tr>
        <td><%= writer.name %></td>
        <td><%= writer.bio %></td>
        <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/writers/new.html.erb
<div class="container">
  <%= form_with scope: :writer, url: writers_path, local: true do |form| %>
    <% if @writer.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@writer.errors.count, "error") %> prohibited
          this writer from being saved:
        </h2>
        <ul>
          <% @writer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <label for="name" class="col-sm-2 col-form-label">作者姓名</label>
      <div class="col-sm-10">
        <%= form.text_field :name, class: "form-control", placeholder: "作者姓名" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="desc" class="col-sm-2 col-form-label">作者简介</label>
      <div class="col-sm-10">
        <%= form.text_area :bio, class: "form-control", placeholder: "作者简介", rows: 3 %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">创建作者</button>
      </div>
    </div>
  <% end %>
</div>